/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_clientmethodhandler_free(a: number): void;
export function createClient(a: number, b: number, c: number): void;
export function destroyClient(a: number): number;
export function callClientMethodAsync(a: number, b: number, c: number, d: number): void;
export function listenMqtt(a: number, b: number, c: number): void;
export function __wbg_secretmanagermethodhandler_free(a: number): void;
export function createSecretManager(a: number, b: number, c: number): void;
export function callSecretManagerMethodAsync(a: number, b: number, c: number, d: number): void;
export function migrateStrongholdSnapshotV2ToV3(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): void;
export function callUtilsMethodRust(a: number, b: number, c: number): void;
export function __wbg_walletmethodhandler_free(a: number): void;
export function createWallet(a: number, b: number, c: number): void;
export function destroyWallet(a: number): number;
export function getClientFromWallet(a: number): number;
export function getSecretManagerFromWallet(a: number): number;
export function callWalletMethodAsync(a: number, b: number, c: number): number;
export function listenWalletAsync(a: number, b: number, c: number): number;
export function migrateDbChrysalisToStardust(a: number, b: number, c: number, d: number, e: number): void;
export function start(): void;
export function initLogger(a: number, b: number): number;
export function __wbindgen_export_0(a: number, b: number): number;
export function __wbindgen_export_1(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __wbindgen_export_3(a: number, b: number): void;
export function __wbindgen_export_4(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_export_5(a: number, b: number, c: number): void;
export function __wbindgen_export_6(a: number): void;
export function __wbindgen_export_7(a: number, b: number, c: number, d: number): void;
export function __wbindgen_start(): void;
